sudo: required
services:
  - docker


before_install:
  - docker build -t ahoobing/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ahoobing/react-test npm test -- --coverage

after_success:
  - docker build -t ahoobing/multi-client ./client
  - docker build -t ahoobing/multi-nginx ./nginx
  - docker build -t ahoobing/multi-server ./server
  - docker buidl -t ahoobing/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ahoobing/multi-client
  - docker push ahoobing/multi-nginx
  - docker push ahoobing/multi-server
  - docker push ahoobing/multi-worker
